name: Latest YouTube Videos
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull youtube videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCWvmWHYhnu8-j_ZZ-2VaHJw"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy" 
          template: "<tr><td><a href=\"$url\"><img width=\"140px\" src=\"https://i.ytimg.com/vi/$videoId/mqdefault.jpg\"></a></td>$newline<td><a href=\"$url\">$title</a><br/>$date</td></tr>$newline" 
          committer_email: "adityads@ymail.com"
